### ISSUE TITLE
repository 'https://github.com/LizardByte/homebrew-homebrew/' not found

### ISSUE THREAD

**Issue by BlackdeerY** [LizardByte/homebrew#7] opened 2024-03-14 08:13 UTC
### Describe the Bug

****@******** ****** % brew tap LizardByte/homebrew
==> Tapping lizardbyte/homebrew
Cloning into '/opt/homebrew/Library/Taps/lizardbyte/homebrew-homebrew'...
Username for 'https://github.com': BlackdeerY
Password for 'https://BlackdeerY@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/LizardByte/homebrew-homebrew/' not found
Error: Failure while executing; `git clone https://github.com/LizardByte/homebrew-homebrew /opt/homebrew/Library/Taps/lizardbyte/homebrew-homebrew --origin=origin --template= --config core.fsmonitor=false` exited with 128.

**Comment by ReenigneArcher** [comment] 2024-03-14 11:40
Duplicate of #5

**Closed by ReenigneArcher** 2024-03-14 11:40 UTC
